version: "3.5"

services:
  nadeko:
    build: .
    depends_on:
      - redis
    restart: on-failure
    volumes:
      - ./credentials.json:/home/nadeko/app/credentials.json:ro
      - nadeko-data:/home/nadeko/app/data
      # Underscore to prevent accidental deletion
      - _nadeko-db:/home/nadeko/app/db/
    environment:
      NadekoBot_RedisOptions: redis,name=nadeko
      NadekoBot_ShardRunCommand: dotnet
      NadekoBot_ShardRunArguments: NadekoBot.dll {0} {1}

  redis:
    image: redis:alpine
    sysctls:
      net.core.somaxconn: 511
    ports:
      - "6379:6379/tcp"

volumes:
  nadeko-data:
  _nadeko-db:
